// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-11-05 11:14:24.095746 +0800 CST m=+0.075339572

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取客户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系电话",
                        "name": "mobile",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerListResponse"
                        }
                    }
                }
            }
        },
        "/customers/checkin_record": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer checkin record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取签到记录",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CheckinRecordResponse"
                        }
                    }
                }
            }
        },
        "/customers/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取客户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户ID,客户访问时可不传",
                        "name": "customer_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerDetailResponse"
                        }
                    }
                }
            }
        },
        "/files/download": {
            "get": {
                "description": "download file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filename",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"avatar\", \"poster\"",
                        "description": "file type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.BaseResponse"
                        }
                    }
                }
            }
        },
        "/files/upload": {
            "post": {
                "description": "upload file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "upload file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"avatar\", \"poster\"",
                        "description": "file type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.BaseResponse"
                        }
                    }
                }
            }
        },
        "/merchants": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get merchant list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "获取商户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户名",
                        "name": "store_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系人",
                        "name": "contact_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系电话",
                        "name": "contact_phone",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantListResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create new merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "新增商户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MerchantVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantAddResponse"
                        }
                    }
                }
            }
        },
        "/merchants/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get merchant detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "获取商户详情信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户ID,商户访问时可不传",
                        "name": "merchant_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantDetailResponse"
                        }
                    }
                }
            }
        },
        "/merchants/login": {
            "post": {
                "description": "merchant login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MerchantLoginVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantLoginResponse"
                        }
                    }
                }
            }
        },
        "/merchants/writeoff": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "merchant get customer write off",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户获取核销信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户ID",
                        "name": "customer_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.WriteOffResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "merchant exec write off",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户核销",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ExecWriteOffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.ExecWriteOffResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户"
                ],
                "summary": "后台用户登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginResponse"
                        }
                    }
                }
            }
        },
        "/verify_code": {
            "get": {
                "description": "send sms code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "验证码"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CodeResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jwt.TokenParames": {
            "type": "object",
            "properties": {
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "uid": {
                    "description": "uid",
                    "type": "integer"
                }
            }
        },
        "model.CheckinRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "customer_id": {
                    "description": "签到人ID",
                    "type": "integer"
                },
                "day": {
                    "description": "签到第几天",
                    "type": "integer"
                },
                "help_checkin_customer_id": {
                    "description": "帮签人ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.Customer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "last_checkin_time": {
                    "description": "最后一次签到时间",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "name": {
                    "description": "称呼",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.IssueRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "customer_id": {
                    "description": "顾客ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "merchant_id": {
                    "description": "店铺ID",
                    "type": "integer"
                },
                "received": {
                    "description": "在对应店铺已兑换的礼品数",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_receive": {
                    "description": "在对应店铺可领取的总礼品数",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.Merchant": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "catering_type": {
                    "description": "餐饮类型",
                    "type": "string"
                },
                "checkin_days": {
                    "description": "签到天数多少天可领取礼品",
                    "type": "integer"
                },
                "checkin_num": {
                    "description": "达到指定签到天数后，可领取的礼品数量",
                    "type": "integer"
                },
                "contact_name": {
                    "description": "联系人",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系人电话",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "description": "纬度",
                    "type": "number"
                },
                "lon": {
                    "description": "经度",
                    "type": "number"
                },
                "poster": {
                    "description": "商户海报",
                    "type": "string"
                },
                "received": {
                    "description": "已领礼品数量",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "store_avatar": {
                    "description": "店铺头像",
                    "type": "string"
                },
                "store_name": {
                    "description": "店名",
                    "type": "string"
                },
                "total_receive": {
                    "description": "该店礼品一共可领取总数",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.MerchantLoginVO": {
            "type": "object",
            "required": [
                "code",
                "contact_phone"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "验证码"
                },
                "contact_phone": {
                    "type": "string",
                    "example": "手机号"
                }
            }
        },
        "model.MerchantVO": {
            "type": "object",
            "required": [
                "address",
                "contact_phone",
                "lat",
                "lon",
                "store_avatar",
                "store_name",
                "total_receive"
            ],
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "catering_type": {
                    "description": "餐饮类型",
                    "type": "string"
                },
                "checkin_days": {
                    "description": "签到天数多少天可领取礼品",
                    "type": "integer"
                },
                "checkin_num": {
                    "description": "达到指定签到天数后，可领取的礼品数量",
                    "type": "integer"
                },
                "contact_name": {
                    "description": "联系人",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系人电话",
                    "type": "string"
                },
                "lat": {
                    "description": "纬度",
                    "type": "number"
                },
                "lon": {
                    "description": "经度",
                    "type": "number"
                },
                "poster": {
                    "description": "商户海报",
                    "type": "string"
                },
                "received": {
                    "description": "已领礼品数量",
                    "type": "integer"
                },
                "store_avatar": {
                    "description": "店铺头像",
                    "type": "string"
                },
                "store_name": {
                    "description": "店名",
                    "type": "string"
                },
                "total_receive": {
                    "description": "该店礼品一共可领取总数",
                    "type": "integer"
                }
            }
        },
        "model.MerchantWriteOffRespVO": {
            "type": "object",
            "properties": {
                "customer": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                },
                "issue_record": {
                    "type": "object",
                    "$ref": "#/definitions/model.IssueRecord"
                },
                "merchant": {
                    "type": "object",
                    "$ref": "#/definitions/model.Merchant"
                }
            }
        },
        "server.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "server.CheckinRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CheckinRecord"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "current": {
                    "description": "当前页页码",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Customer"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "server.ExecWriteOffRequest": {
            "type": "object",
            "properties": {
                "tokenParames": {
                    "type": "object",
                    "$ref": "#/definitions/jwt.TokenParames"
                }
            }
        },
        "server.ExecWriteOffResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantWriteOffRespVO"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantAddResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.Merchant"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "current": {
                    "description": "当前页页码",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Merchant"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "server.MerchantLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "description": "access token",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.UserLoginRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "server.UserLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "description": "access token",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.WriteOffResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantWriteOffRespVO"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "福利签API文档",
	Description: "福利签API文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
