// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2019-11-30 18:30:37.294648 +0800 CST m=+0.093904358

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customers": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取客户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系电话",
                        "name": "mobile",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "客户状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerListResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "删除客户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.CustomerDelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerDelResponse"
                        }
                    }
                }
            }
        },
        "/customers/checkin_record": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer checkin record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取签到记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当该参数有值时以该参数为准，否则以token用户为准",
                        "name": "customer_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CheckinRecordResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer exec checkin record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "用户执行签到",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.ExecCheckinRecordResponse"
                        }
                    }
                }
            }
        },
        "/customers/checkin_record/help": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer help other checkin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "为他人补签",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.HelpCheckinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.HelpCheckinResponse"
                        }
                    }
                }
            }
        },
        "/customers/checkin_record/refresh": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer refresh checkin record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "用户重新签到",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.RefreshCheckinRecordResponse"
                        }
                    }
                }
            }
        },
        "/customers/detail": {
            "get": {
                "description": "get customer detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取客户详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "客户ID,客户访问时可不传",
                        "name": "customer_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerDetailResponse"
                        }
                    }
                }
            }
        },
        "/customers/disable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "disable customer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "禁用客户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.CustomerDisableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerDisableResponse"
                        }
                    }
                }
            }
        },
        "/customers/issue_records": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer get issue record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "客户查看我的福利",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.IssueRecordResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer exec issue record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "用户领取福利",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ExecIssueRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.ExecIssueRecordResponse"
                        }
                    }
                }
            }
        },
        "/customers/issue_records/is_supplement": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "is supplement checkin",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "是否是补签",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.IsSupplementCheckinResponse"
                        }
                    }
                }
            }
        },
        "/customers/login": {
            "post": {
                "description": "customer login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "客户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "微信回调code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CustomerLoginResponse"
                        }
                    }
                }
            }
        },
        "/customers/near_merchant": {
            "get": {
                "description": "get customer near merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取用户附近最近的几家店铺",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "经度",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "维度",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "距离多少公里内，默认10",
                        "name": "distince",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回数量，默认4个",
                        "name": "num",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.NearMerchantResponse"
                        }
                    }
                }
            }
        },
        "/customers/qrcode": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get customer qrcode",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户"
                ],
                "summary": "获取客户所属二维码",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/files/download": {
            "get": {
                "description": "download file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "下载文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "filename",
                        "name": "filename",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"avatar\", \"poster\"",
                        "description": "file type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.BaseResponse"
                        }
                    }
                }
            }
        },
        "/files/upload": {
            "post": {
                "description": "upload file",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "file",
                        "description": "upload file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"avatar\", \"poster\"",
                        "description": "file type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.BaseResponse"
                        }
                    }
                }
            }
        },
        "/merchants": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get merchant list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "获取商户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户名",
                        "name": "store_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系人",
                        "name": "contact_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "联系电话",
                        "name": "contact_phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "商户状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page_no",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "页数",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantListResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "edit merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "编辑商户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.MerchantEditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantEditResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "create new merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "新增商户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.MerchantAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantAddResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "delete merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "删除商户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.MerchantDelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantDelResponse"
                        }
                    }
                }
            }
        },
        "/merchants/detail": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get merchant detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "获取商户详情信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "商户ID,商户访问时可不传",
                        "name": "merchant_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantDetailResponse"
                        }
                    }
                }
            }
        },
        "/merchants/disable": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "disable merchant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "禁用商户",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.MerchantDisableRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantDisableResponse"
                        }
                    }
                }
            }
        },
        "/merchants/login": {
            "post": {
                "description": "merchant login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.MerchantLoginVO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.MerchantLoginResponse"
                        }
                    }
                }
            }
        },
        "/merchants/poster": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get merchant poster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "获取商户随机一张海报",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/merchants/writeoff": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "merchant get customer write off",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户获取核销信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户ID",
                        "name": "customer_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.WriteOffResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "merchant exec write off",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商户"
                ],
                "summary": "商户核销",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ExecWriteOffRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.ExecWriteOffResponse"
                        }
                    }
                }
            }
        },
        "/users/checkin_record_list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "get checkin record list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户"
                ],
                "summary": "获取签到记录列表(临时)",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CheckinRecordListResponse"
                        }
                    }
                }
            }
        },
        "/users/checkin_record_list/modify": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "users modify customer checkin record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户"
                ],
                "summary": "后台用户更改用户签到记录(临时)",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.ModifyCheckinRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.ModifyCheckinRecordResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "user login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户"
                ],
                "summary": "后台用户登录",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.UserLoginResponse"
                        }
                    }
                }
            }
        },
        "/verify_code": {
            "get": {
                "description": "send sms code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "验证码"
                ],
                "summary": "发送验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "手机号",
                        "name": "mobile",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.CodeResponse"
                        }
                    }
                }
            }
        },
        "/wx/config": {
            "get": {
                "description": "get wx config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信"
                ],
                "summary": "获取微信接口配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前页URL，不包含#及其后面部分",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.WXConfigResponse"
                        }
                    }
                }
            }
        },
        "/wx/pay": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "customer pay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信"
                ],
                "summary": "用户支付",
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "$ref": "#/definitions/server.WXPayResponse"
                        }
                    }
                }
            }
        },
        "/wx/pay/notify": {
            "post": {
                "description": "wx pay callback",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "微信"
                ],
                "summary": "用户支付",
                "parameters": [
                    {
                        "description": "参数",
                        "name": "args",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/server.WxpayCallbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"status\":true}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "jwt.TokenParames": {
            "type": "object",
            "properties": {
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "name": {
                    "description": "姓名",
                    "type": "string"
                },
                "uid": {
                    "description": "uid",
                    "type": "integer"
                }
            }
        },
        "model.CheckinRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "customer_id": {
                    "description": "签到人ID",
                    "type": "integer"
                },
                "day": {
                    "description": "签到第几天",
                    "type": "integer"
                },
                "help_checkin_customer_id": {
                    "description": "帮签人ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "need_checkin_time": {
                    "description": "需要签到的日期",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.CheckinRecordListResp": {
            "type": "object",
            "properties": {
                "checkin_record": {
                    "type": "object",
                    "$ref": "#/definitions/model.CheckinRecord"
                },
                "customer": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                }
            }
        },
        "model.Customer": {
            "type": "object",
            "properties": {
                "city": {
                    "description": "微信用户所在区",
                    "type": "string"
                },
                "country": {
                    "description": "微信用户所在国家",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "headimgurl": {
                    "description": "微信用户头像",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_checkin_time": {
                    "description": "最后一次签到时间",
                    "type": "string"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "name": {
                    "description": "称呼",
                    "type": "string"
                },
                "nickname": {
                    "description": "微信用户昵称",
                    "type": "string"
                },
                "open_id": {
                    "description": "微信用户openid",
                    "type": "string"
                },
                "province": {
                    "description": "微信用户所在市",
                    "type": "string"
                },
                "sex": {
                    "description": "微信用户性别",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.IssueRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "customer": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                },
                "customer_id": {
                    "description": "顾客ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "merchant": {
                    "type": "object",
                    "$ref": "#/definitions/model.Merchant"
                },
                "merchant_id": {
                    "description": "店铺ID",
                    "type": "integer"
                },
                "received": {
                    "description": "在对应店铺已兑换的礼品数",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "total_receive": {
                    "description": "在对应店铺可领取的总礼品数",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.Merchant": {
            "type": "object",
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "catering_type": {
                    "description": "餐饮类型",
                    "type": "string"
                },
                "checkin_days": {
                    "description": "签到天数多少天可领取礼品",
                    "type": "integer"
                },
                "checkin_num": {
                    "description": "达到指定签到天数后，可领取的礼品数量",
                    "type": "integer"
                },
                "contact_name": {
                    "description": "联系人",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系人电话",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "has_failure": {
                    "description": "已失效",
                    "type": "integer"
                },
                "has_write_off_num": {
                    "description": "已核销总数",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "description": "纬度",
                    "type": "number"
                },
                "lon": {
                    "description": "经度",
                    "type": "number"
                },
                "poster": {
                    "description": "商户海报",
                    "type": "string"
                },
                "received": {
                    "description": "已领礼品数量",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "store_avatar": {
                    "description": "店铺头像",
                    "type": "string"
                },
                "store_name": {
                    "description": "店名",
                    "type": "string"
                },
                "total_receive": {
                    "description": "该店礼品一共可领取总数",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "integer"
                }
            }
        },
        "model.MerchantLoginVO": {
            "type": "object",
            "required": [
                "code",
                "contact_phone"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "验证码"
                },
                "contact_phone": {
                    "type": "string",
                    "example": "手机号"
                }
            }
        },
        "model.MerchantVO": {
            "type": "object",
            "required": [
                "address",
                "checkin_days",
                "checkin_num",
                "contact_phone",
                "lat",
                "lon",
                "store_avatar",
                "store_name",
                "total_receive"
            ],
            "properties": {
                "address": {
                    "description": "地址",
                    "type": "string"
                },
                "catering_type": {
                    "description": "餐饮类型",
                    "type": "string"
                },
                "checkin_days": {
                    "description": "签到天数多少天可领取礼品",
                    "type": "integer"
                },
                "checkin_num": {
                    "description": "达到指定签到天数后，可领取的礼品数量",
                    "type": "integer"
                },
                "contact_name": {
                    "description": "联系人",
                    "type": "string"
                },
                "contact_phone": {
                    "description": "联系人电话",
                    "type": "string"
                },
                "lat": {
                    "description": "纬度",
                    "type": "number"
                },
                "lon": {
                    "description": "经度",
                    "type": "number"
                },
                "poster": {
                    "description": "商户海报",
                    "type": "string"
                },
                "store_avatar": {
                    "description": "店铺头像",
                    "type": "string"
                },
                "store_name": {
                    "description": "店名",
                    "type": "string"
                },
                "total_receive": {
                    "description": "该店礼品一共可领取总数",
                    "type": "integer"
                }
            }
        },
        "model.MerchantWriteOffRespVO": {
            "type": "object",
            "properties": {
                "customer": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                },
                "issue_record": {
                    "type": "object",
                    "$ref": "#/definitions/model.IssueRecord"
                },
                "merchant": {
                    "type": "object",
                    "$ref": "#/definitions/model.Merchant"
                },
                "num": {
                    "type": "integer"
                }
            }
        },
        "model.WXConfigResp": {
            "type": "object",
            "properties": {
                "appid": {
                    "description": "公众号的唯一标识",
                    "type": "string"
                },
                "noncestr": {
                    "description": "生成签名的随机串",
                    "type": "string"
                },
                "signature": {
                    "description": "签名",
                    "type": "string"
                },
                "timestamp": {
                    "description": "生成签名的时间戳",
                    "type": "integer"
                }
            }
        },
        "server.BaseResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {
                    "type": "object"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "server.CheckinRecordListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CheckinRecordListResp"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CheckinRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CheckinRecord"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerDelRequest": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "description": "客户ID",
                    "type": "integer"
                }
            }
        },
        "server.CustomerDelResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.Customer"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerDisableRequest": {
            "type": "object",
            "properties": {
                "customer_id": {
                    "description": "客户ID",
                    "type": "integer"
                }
            }
        },
        "server.CustomerDisableResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.CustomerListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "current": {
                    "description": "当前页页码",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Customer"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "server.CustomerLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.ExecCheckinRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.ExecIssueRecordRequest": {
            "type": "object",
            "required": [
                "merchant_id"
            ],
            "properties": {
                "code": {
                    "description": "验证码",
                    "type": "string"
                },
                "merchant_id": {
                    "description": "店铺ID",
                    "type": "integer"
                },
                "mobile": {
                    "description": "手机号",
                    "type": "string"
                }
            }
        },
        "server.ExecIssueRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.ExecWriteOffRequest": {
            "type": "object",
            "required": [
                "customer_id",
                "num"
            ],
            "properties": {
                "customer_id": {
                    "description": "客户ID",
                    "type": "integer"
                },
                "num": {
                    "description": "核销数目",
                    "type": "integer"
                }
            }
        },
        "server.ExecWriteOffResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantWriteOffRespVO"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.HelpCheckinRequest": {
            "type": "object",
            "required": [
                "customer_id"
            ],
            "properties": {
                "customer_id": {
                    "description": "补签客户ID",
                    "type": "integer"
                }
            }
        },
        "server.HelpCheckinResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.IsSupplementCheckinResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "boolean"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.IssueRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.IssueRecord"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantAddRequest": {
            "type": "object",
            "properties": {
                "merchant": {
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantVO"
                }
            }
        },
        "server.MerchantAddResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantDelRequest": {
            "type": "object",
            "properties": {
                "merchant_id": {
                    "description": "商户ID",
                    "type": "integer"
                }
            }
        },
        "server.MerchantDelResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.Merchant"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantDisableRequest": {
            "type": "object",
            "properties": {
                "merchant_id": {
                    "description": "商户ID",
                    "type": "integer"
                }
            }
        },
        "server.MerchantDisableResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantEditRequest": {
            "type": "object",
            "properties": {
                "merchant": {
                    "description": "商户信息",
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantVO"
                },
                "merchant_id": {
                    "description": "商户ID",
                    "type": "integer"
                }
            }
        },
        "server.MerchantEditResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.MerchantListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "current": {
                    "description": "当前页页码",
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Merchant"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                },
                "total": {
                    "description": "总数量",
                    "type": "integer"
                }
            }
        },
        "server.MerchantLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "description": "access token",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.ModifyCheckinRecordRequest": {
            "type": "object",
            "properties": {
                "checkin_record_id": {
                    "description": "签到记录ID",
                    "type": "integer"
                },
                "status": {
                    "description": "用户状态：U，A",
                    "type": "string"
                }
            }
        },
        "server.ModifyCheckinRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.NearMerchantResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Merchant"
                    }
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.RefreshCheckinRecordResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.UserLoginRequest": {
            "type": "object",
            "required": [
                "name",
                "password"
            ],
            "properties": {
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "server.UserLoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "description": "access token",
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.WXConfigResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.WXConfigResp"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.WXPayResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.WriteOffResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "type": "string"
                },
                "data": {
                    "type": "object",
                    "$ref": "#/definitions/model.MerchantWriteOffRespVO"
                },
                "error": {
                    "description": "Error信息",
                    "type": "string"
                },
                "message": {
                    "description": "提示消息",
                    "type": "string"
                },
                "status": {
                    "description": "状态",
                    "type": "boolean"
                }
            }
        },
        "server.WxpayCallbackRequest": {
            "type": "object",
            "properties": {
                "params": {
                    "type": "string"
                },
                "response": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/v1",
	Schemes:     []string{},
	Title:       "福利签API文档",
	Description: "福利签API文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
